// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpONL2WpdV4XWZFDIDTL3qRJxdnSoPDuc',
    appId: '1:637666646239:web:8274e3f50012b6d2e3b16a',
    messagingSenderId: '637666646239',
    projectId: 'instagram-tut-af788',
    authDomain: 'instagram-tut-af788.firebaseapp.com',
    storageBucket: 'instagram-tut-af788.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjqXMdqxUOSPAL_2dMVXP7Cu0sOqU55To',
    appId: '1:637666646239:android:b3c3294b332eafbee3b16a',
    messagingSenderId: '637666646239',
    projectId: 'instagram-tut-af788',
    storageBucket: 'instagram-tut-af788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZfqyGLOHX2Kevys8_LRo-N_Lmfrib2aM',
    appId: '1:637666646239:ios:0d04f6d10ab77b9ae3b16a',
    messagingSenderId: '637666646239',
    projectId: 'instagram-tut-af788',
    storageBucket: 'instagram-tut-af788.appspot.com',
    iosClientId: '637666646239-52219gjfjl1so3m4qngg1nsc3qvpqimd.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
