// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYuEayKceHCEMY7QZv3JcUgE3V-bH6la0',
    appId: '1:169936880735:web:de20f039e66fc0db5ec7ea',
    messagingSenderId: '169936880735',
    projectId: 'instagram-dc53a',
    authDomain: 'instagram-dc53a.firebaseapp.com',
    storageBucket: 'instagram-dc53a.appspot.com',
    measurementId: 'G-4NK6LJSBBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALdFj-KpFSMUT5qgBW_2LU0wdBPvnppzg',
    appId: '1:169936880735:android:11e1cb544861fd265ec7ea',
    messagingSenderId: '169936880735',
    projectId: 'instagram-dc53a',
    storageBucket: 'instagram-dc53a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTjR_GGHryinj9O2yw4HZ5u1BpMJ4Gt4k',
    appId: '1:169936880735:ios:05c7eaaefd2ef7f05ec7ea',
    messagingSenderId: '169936880735',
    projectId: 'instagram-dc53a',
    storageBucket: 'instagram-dc53a.appspot.com',
    iosClientId: '169936880735-b4q2ovl1e1q67advios56lt6td8731s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutterClone',
  );
}
